name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: echo "Build Successful"